[directory]
read_only = " ó°Œ¾"
style = "bold #89b4fa"

[directory.substitutions]
"~" = "ï€• ~"
"Documents" = "ó°° "
"Downloads" = "ï€™ "
"Music" = "ğŸœ "
"Pictures" = "ï‘† "
"Videos" = "ï€½ "
"Notes" = "ó° ®"

[character]
success_symbol = '[â¯](#a6e3a1) '
error_symbol = '[â¯](#f38ba8) '

[fossil_branch]
symbol = "ï˜ "
style = "bold #94e2d5"  # Teal

[git_branch]
symbol = "ï˜ "
style = "bold #94e2d5"  # Teal

[git_status]
style = "fg:#94e2d5"
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï£– '
modified = 'ï„ '
renamed = 'ïª¶ '
deleted = 'ï€” '
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bold #bd93f9"  # Green

[hg_branch]
symbol = "ï˜ "
style = "bold #f38ba8"  # Red

[hostname]
ssh_symbol = "î¬ "
style = "bold #94e2d5"  # Teal

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "
style = "bold #bd93f9"

[php]
symbol = "î˜ˆ "
style = "bold #bd93f9"

[python]
symbol = "îˆµ "
style = "bold #bd93f9"

[ruby]
symbol = "î‘ "
style = "bold #bd93f9"

[rust]
symbol = "ó±˜— "
style = "bold #bd93f9"

[aws]
symbol = "îŒ½  "
style = "bold #bd93f9"

[c]
symbol = "î˜ "
style = "bold #bd93f9"

[conda]
symbol = "ï„Œ "
style = "bold #bd93f9"

[docker_context]
symbol = "ïŒˆ "
style = "bold #89b4fa"  # Blue

[java]
symbol = "î‰– "
style = "bold #bd93f9"

[lua]
symbol = "î˜  "
style = "bold #bd93f9"

[nodejs]
symbol = "îœ˜ "
style = "bold #bd93f9"

[cmd_duration]
min_time = 500
style = "bold #bd93f9"
disabled = false
